[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solve = "37Vvm7sLoryNKFQLQhmrgG94rcL1FgcR9jgFFbQq5e8u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/q7/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
